Update README.md
shakebugs/shake-ios pull request #9
Opened 2020-12-16 08:53 UTC by domagojKo

2020-12-16 09:00 UTC, david-decode commented on README.md
> +#### Temporary workaround
Add a snippet from documentation that explains in which Xcode version does this happen and which one eliminated this bug.

2020-12-16 09:00 UTC, david-decode commented on README.md
> -
At the below snippet to the bottom of this document


Check out the full documentation -> https://www.shakebugs.com/docs/

2021-01-11 13:22 UTC, mstanic0 requested changes

2021-01-11 13:48 UTC, domagojKo commented on README.md
> +### Swift Package Manager
Check readme.md, we have this section.

2021-01-12 11:11 UTC, merged